import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import download from "../../public/Static/images/download.png";
import { fetchCurrentWord } from "../fetch";
import ResultsObjects from "../../components/ResultObjects";
import { useState } from "react";

export default function SearchPage(props: any) {
  const [currentUserSearch, setCurrentUserSearch] = useState<string>("");
  const [clicked, setClicked] = useState<boolean>(false);
  const [resultsObject, setResultsObject] = useState<any>(null);

  const fetchUserSearch = async () => {
    setClicked(true);
    const userSearch = await fetchCurrentWord(currentUserSearch);
    // Update State
    if (userSearch.result) {
      setResultsObject(userSearch);
    } else {
      setResultsObject(null);
    }
  };

  return (
    <div>
      <Head>
        <title>Search Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Static/images/chucky2.png" />
      </Head>
      <main className={styles.searchpage}>
        <header className={styles.header}>
          <Image className={styles.logo} alt="logo" src={download}></Image>
          <div>
            <Link href="/">
              <button className={styles.button} type="button">
                Home Page
              </button>
            </Link>
            <Link href="/Categories">
              <button className={styles.button} type="button">
                Categories
              </button>
            </Link>
          </div>
        </header>
        <div style={{ flexDirection: "row" }}>
          <h3 className={styles.title}>Search Page</h3>
          <h3 style={{ textAlign: "center" }}>
            Use a keyword to find the joke you are looking for!
          </h3>
          <div className={styles.formdiv} style={{ width: "100%" }}>
            <div className={styles.searchform}>
              <input
                type="text"
                className={styles.searchforminput}
                onChange={(event) => {
                  setClicked(false);
                  setCurrentUserSearch(event.target.value);
                }}
              />
              <button
                className={styles.searchformbutton}
                onClick={() => fetchUserSearch()}
              >
                <i className="fa fa-search"></i>Search Joke
              </button>
            </div>

            <ResultsObjects
              currentUserSearch={currentUserSearch}
              setCurrentUserSearch={setCurrentUserSearch}
              clicked={clicked}
              setClicked={setClicked}
              resultsObject={resultsObject}
              setResultsObject={setResultsObject}
            ></ResultsObjects>
          </div>
        </div>
      </main>
    </div>
  );
}
